config/routes.rb
Lighthouse::Application.routes.draw do
  resources :student_cell_leaders

  resources :student_pastors

  resources :cell_leaders

  resources :students do
    resources :student_cards
  end

  resources :pastors

  get "index/indexpage"

  devise_for :users

   root :to => 'home#index'

end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :email, :mobile, :name
  has_many :student_cards

  has_many :student_pastors
  has_many :pastors, :through => :student_pastors

  has_many :student_cell_leaders
  has_many :cell_leaders, :through => :student_cell_leaders

  validates :email, :mobile, :name, presence: true
  validate :email, :email_validator, uniqueness: true

  def email_validator
    errors.add(:email, "not a valid email") unless email =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # GET /students
  # GET /students.json
  def index
    @students = Student.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @students }
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student = Student.find(params[:id])
    @student_cards = @student.student_cards

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/new
  # GET /students/new.json
  def new
    @student = Student.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render json: @student, status: :created, location: @student }
      else
        format.html { render action: "new" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.json
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= simple_form_for(@student) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :mobile %>
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Mobile</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @students.each do |student| %>
  <tr>
    <td><%= student.name %></td>
    <td><%= student.mobile %></td>
    <td><%= student.email %></td>
    <td><%= link_to 'Show', student %></td>
    <td><%= link_to 'Edit', edit_student_path(student) %></td>
    <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<div class="row-fluid">
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>
</div>

app/views/students/show.html.erb
<div class="row-fluid">
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @student.name %>
</p>

<p>
  <b>Mobile:</b>
  <%= @student.mobile %>
</p>

<p>
  <b>Email:</b>
  <%= @student.email %>
</p>

<h1>Listing student_cards</h1>

<table class="table table-stripped table-bordered table-condensed table-hover">
  <tr>
      <th>Attendance</th>
    <th>Days journaled</th>
      <th>Days prayed</th>
    <th>Attended cell</th>
      <th>Attended church</th>
    <th>Assignment one</th>
      <th>Assignment two</th>
    <th>Memory verse</th>
      <th>Test</th>
    <th>Bible reading</th>
      <th></th>
    <th></th>
</tr>

<% @student_cards.each do |student_card| %>
  <tr>
      <td><%= student_card.attendance %></td>
      <td><%= student_card.days_journaled %></td>
      <td><%= student_card.days_prayed %></td>
      <td><%= student_card.attended_cell %></td>
      <td><%= student_card.attended_church %></td>
      <td><%= student_card.assignment_one %></td>
      <td><%= student_card.assignment_two %></td>
      <td><%= student_card.memory_verse %></td>
      <td><%= student_card.test %></td>
      <td><%= student_card.bible_reading %></td>
      <td><%= link_to 'Show', [@student, student_card] %></td>
      <td><%= link_to 'Edit', edit_student_student_card_path(@student, student_card) %></td>
    <td><%= link_to 'Destroy', [@student, student_card], method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>
<% end %>
</table>

  <br />

<%= link_to 'Add an entry', new_student_student_card_path(@student) %> |
<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>
</div>