config/routes.rb
Lighthouse::Application.routes.draw do
  resources :student_cell_leaders

  resources :student_pastors

  resources :cell_leaders

  resources :students do
    resources :student_cards
  end

  resources :pastors

  get "index/indexpage"

  devise_for :users

   root :to => 'home#index'

end

app/models/student_cell_leader.rb
class StudentCellLeader < ActiveRecord::Base
  belongs_to :student
  belongs_to :cell_leader

  attr_accessible :date

  validates :student_id, :cell_leader_id, :date, presence: true

  before_validation :set_date


  def set_date
    self.date = Time.now.to_date
  end
end

app/controllers/student_cell_leaders_controller.rb
class StudentCellLeadersController < ApplicationController
  # GET /student_cell_leaders
  # GET /student_cell_leaders.json
  def index
    @student_cell_leaders = StudentCellLeader.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @student_cell_leaders }
    end
  end

  # GET /student_cell_leaders/1
  # GET /student_cell_leaders/1.json
  def show
    @student_cell_leader = StudentCellLeader.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student_cell_leader }
    end
  end

  # GET /student_cell_leaders/new
  # GET /student_cell_leaders/new.json
  def new
    @student_cell_leader = StudentCellLeader.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student_cell_leader }
    end
  end

  # GET /student_cell_leaders/1/edit
  def edit
    @student_cell_leader = StudentCellLeader.find(params[:id])
  end

  # POST /student_cell_leaders
  # POST /student_cell_leaders.json
  def create
    @student_cell_leader = StudentCellLeader.new(params[:student_cell_leader])

    respond_to do |format|
      if @student_cell_leader.save
        format.html { redirect_to @student_cell_leader, notice: 'Student cell leader was successfully created.' }
        format.json { render json: @student_cell_leader, status: :created, location: @student_cell_leader }
      else
        format.html { render action: "new" }
        format.json { render json: @student_cell_leader.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /student_cell_leaders/1
  # PUT /student_cell_leaders/1.json
  def update
    @student_cell_leader = StudentCellLeader.find(params[:id])

    respond_to do |format|
      if @student_cell_leader.update_attributes(params[:student_cell_leader])
        format.html { redirect_to @student_cell_leader, notice: 'Student cell leader was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student_cell_leader.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_cell_leaders/1
  # DELETE /student_cell_leaders/1.json
  def destroy
    @student_cell_leader = StudentCellLeader.find(params[:id])
    @student_cell_leader.destroy

    respond_to do |format|
      format.html { redirect_to student_cell_leaders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/student_cell_leaders_helper.rb
module StudentCellLeadersHelper
end

app/views/student_cell_leaders/_form.html.erb
<%= simple_form_for(@student_cell_leader) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :student %>
    <%= f.association :cell_leader %>
    <%= f.input :date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/student_cell_leaders/edit.html.erb
<h1>Editing student_cell_leader</h1>

<%= render 'form' %>

<%= link_to 'Show', @student_cell_leader %> |
<%= link_to 'Back', student_cell_leaders_path %>

app/views/student_cell_leaders/index.html.erb
<h1>Listing student_cell_leaders</h1>

<table>
  <tr>
    <th>Student</th>
    <th>Cell leader</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @student_cell_leaders.each do |student_cell_leader| %>
  <tr>
    <td><%= student_cell_leader.student %></td>
    <td><%= student_cell_leader.cell_leader %></td>
    <td><%= student_cell_leader.date %></td>
    <td><%= link_to 'Show', student_cell_leader %></td>
    <td><%= link_to 'Edit', edit_student_cell_leader_path(student_cell_leader) %></td>
    <td><%= link_to 'Destroy', student_cell_leader, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student cell leader', new_student_cell_leader_path %>

app/views/student_cell_leaders/new.html.erb
<h1>New student_cell_leader</h1>

<%= render 'form' %>

<%= link_to 'Back', student_cell_leaders_path %>

app/views/student_cell_leaders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Student:</b>
  <%= @student_cell_leader.student %>
</p>

<p>
  <b>Cell leader:</b>
  <%= @student_cell_leader.cell_leader %>
</p>

<p>
  <b>Date:</b>
  <%= @student_cell_leader.date %>
</p>


<%= link_to 'Edit', edit_student_cell_leader_path(@student_cell_leader) %> |
<%= link_to 'Back', student_cell_leaders_path %>