config/routes.rb
Lighthouse::Application.routes.draw do
  resources :student_cell_leaders

  resources :student_pastors

  resources :cell_leaders

  resources :students do
    resources :student_cards
  end

  resources :pastors

  get "index/indexpage"

  devise_for :users

   root :to => 'home#index'

end

app/models/cell_leader.rb
class CellLeader < ActiveRecord::Base
  attr_accessible :email, :mobile, :name

  has_many :student_cell_leaders
  has_many :students, :through => :student_cell_leaders

  validates :email, :mobile, :name, presence: true

  validate :email, :email_validator, uniqueness: true

  def email_validator
    errors.add(:email, "not a valid email") unless email =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  end
end

app/controllers/cell_leaders_controller.rb
class CellLeadersController < ApplicationController
  # GET /cell_leaders
  # GET /cell_leaders.json
  def index
    @cell_leaders = CellLeader.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cell_leaders }
    end
  end

  # GET /cell_leaders/1
  # GET /cell_leaders/1.json
  def show
    @cell_leader = CellLeader.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cell_leader }
    end
  end

  # GET /cell_leaders/new
  # GET /cell_leaders/new.json
  def new
    @cell_leader = CellLeader.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cell_leader }
    end
  end

  # GET /cell_leaders/1/edit
  def edit
    @cell_leader = CellLeader.find(params[:id])
  end

  # POST /cell_leaders
  # POST /cell_leaders.json
  def create
    @cell_leader = CellLeader.new(params[:cell_leader])

    respond_to do |format|
      if @cell_leader.save
        format.html { redirect_to @cell_leader, notice: 'Cell leader was successfully created.' }
        format.json { render json: @cell_leader, status: :created, location: @cell_leader }
      else
        format.html { render action: "new" }
        format.json { render json: @cell_leader.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cell_leaders/1
  # PUT /cell_leaders/1.json
  def update
    @cell_leader = CellLeader.find(params[:id])

    respond_to do |format|
      if @cell_leader.update_attributes(params[:cell_leader])
        format.html { redirect_to @cell_leader, notice: 'Cell leader was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cell_leader.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cell_leaders/1
  # DELETE /cell_leaders/1.json
  def destroy
    @cell_leader = CellLeader.find(params[:id])
    @cell_leader.destroy

    respond_to do |format|
      format.html { redirect_to cell_leaders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cell_leaders_helper.rb
module CellLeadersHelper
end

app/views/cell_leaders/_form.html.erb
<%= simple_form_for(@cell_leader) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :mobile %>
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cell_leaders/edit.html.erb
<h1>Editing cell_leader</h1>

<%= render 'form' %>

<%= link_to 'Show', @cell_leader %> |
<%= link_to 'Back', cell_leaders_path %>

app/views/cell_leaders/index.html.erb
<h1>Listing cell_leaders</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Mobile</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cell_leaders.each do |cell_leader| %>
  <tr>
    <td><%= cell_leader.name %></td>
    <td><%= cell_leader.mobile %></td>
    <td><%= cell_leader.email %></td>
    <td><%= link_to 'Show', cell_leader %></td>
    <td><%= link_to 'Edit', edit_cell_leader_path(cell_leader) %></td>
    <td><%= link_to 'Destroy', cell_leader, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cell leader', new_cell_leader_path %>

app/views/cell_leaders/new.html.erb
<h1>New cell_leader</h1>

<%= render 'form' %>

<%= link_to 'Back', cell_leaders_path %>

app/views/cell_leaders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @cell_leader.name %>
</p>

<p>
  <b>Mobile:</b>
  <%= @cell_leader.mobile %>
</p>

<p>
  <b>Email:</b>
  <%= @cell_leader.email %>
</p>


<%= link_to 'Edit', edit_cell_leader_path(@cell_leader) %> |
<%= link_to 'Back', cell_leaders_path %>