config/routes.rb
Lighthouse::Application.routes.draw do
  resources :student_cell_leaders

  resources :student_pastors

  resources :cell_leaders

  resources :students do
    resources :student_cards
  end

  resources :pastors

  get "index/indexpage"

  devise_for :users

   root :to => 'home#index'

end

app/models/student_pastor.rb
class StudentPastor < ActiveRecord::Base
  belongs_to :pastor
  belongs_to :student

  attr_accessible :date

  validates :student_id, :pastor_id, :date, presence: true

  before_validation :set_date

  def set_date
    self.date = Time.now.to_date
  end
end

app/controllers/student_pastors_controller.rb
class StudentPastorsController < ApplicationController
  # GET /student_pastors
  # GET /student_pastors.json
  def index
    @student_pastors = StudentPastor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @student_pastors }
    end
  end

  # GET /student_pastors/1
  # GET /student_pastors/1.json
  def show
    @student_pastor = StudentPastor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student_pastor }
    end
  end

  # GET /student_pastors/new
  # GET /student_pastors/new.json
  def new
    @student_pastor = StudentPastor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student_pastor }
    end
  end

  # GET /student_pastors/1/edit
  def edit
    @student_pastor = StudentPastor.find(params[:id])
  end

  # POST /student_pastors
  # POST /student_pastors.json
  def create
    @student_pastor = StudentPastor.new(params[:student_pastor])

    respond_to do |format|
      if @student_pastor.save
        format.html { redirect_to @student_pastor, notice: 'Student pastor was successfully created.' }
        format.json { render json: @student_pastor, status: :created, location: @student_pastor }
      else
        format.html { render action: "new" }
        format.json { render json: @student_pastor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /student_pastors/1
  # PUT /student_pastors/1.json
  def update
    @student_pastor = StudentPastor.find(params[:id])

    respond_to do |format|
      if @student_pastor.update_attributes(params[:student_pastor])
        format.html { redirect_to @student_pastor, notice: 'Student pastor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student_pastor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_pastors/1
  # DELETE /student_pastors/1.json
  def destroy
    @student_pastor = StudentPastor.find(params[:id])
    @student_pastor.destroy

    respond_to do |format|
      format.html { redirect_to student_pastors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/student_pastors_helper.rb
module StudentPastorsHelper
end

app/views/student_pastors/_form.html.erb
<%= simple_form_for(@student_pastor) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :pastor %>
    <%= f.association :student %>
    <%= f.input :date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/student_pastors/edit.html.erb
<h1>Editing student_pastor</h1>

<%= render 'form' %>

<%= link_to 'Show', @student_pastor %> |
<%= link_to 'Back', student_pastors_path %>

app/views/student_pastors/index.html.erb
<h1>Listing student_pastors</h1>

<table>
  <tr>
    <th>Pastor</th>
    <th>Student</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @student_pastors.each do |student_pastor| %>
  <tr>
    <td><%= student_pastor.pastor %></td>
    <td><%= student_pastor.student %></td>
    <td><%= student_pastor.date %></td>
    <td><%= link_to 'Show', student_pastor %></td>
    <td><%= link_to 'Edit', edit_student_pastor_path(student_pastor) %></td>
    <td><%= link_to 'Destroy', student_pastor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student pastor', new_student_pastor_path %>

app/views/student_pastors/new.html.erb
<h1>New student_pastor</h1>

<%= render 'form' %>

<%= link_to 'Back', student_pastors_path %>

app/views/student_pastors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Pastor:</b>
  <%= @student_pastor.pastor %>
</p>

<p>
  <b>Student:</b>
  <%= @student_pastor.student %>
</p>

<p>
  <b>Date:</b>
  <%= @student_pastor.date %>
</p>


<%= link_to 'Edit', edit_student_pastor_path(@student_pastor) %> |
<%= link_to 'Back', student_pastors_path %>